image: node:latest

build:hello:
  stage: build
  script:
  - apt-get update -qq && apt-get install -y -qq tree
  - node --version
  - npm --version
  - npm install
  - npm install -g @angular/cli 
  - ng build --aot true --environment prod
  